// Package genheader tells the Go files the GALA transpiler writes from every
// other Go file.
//
// A `.gen.go` the transpiler wrote and left in a source tree restates the
// .gala source it came from, so anything that reads a package's Go files
// leaves it out. The name alone does not say which it is: `.gen.go` is also
// the name other generators give their output (oapi-codegen, stringer, protoc
// plugins), and those files are part of the package like hand-written Go. The
// transpiler opens every file it writes with Header, so Stale and StaleFile
// decide on the name and that first line, and every reader of a source tree
// asks them.
package genheader

import (
	"bytes"
	"go/ast"
	"io"
	"os"
	"strings"
)

// Header is the line that opens every Go file the GALA transpiler writes.
const Header = "// Code generated by GALA transpiler. DO NOT EDIT."

// Opens reports whether src, the content of a Go file, opens with Header on a
// line of its own: the file is output of the GALA transpiler.
func Opens(src []byte) bool {
	rest, ok := bytes.CutPrefix(src, []byte(Header))
	return ok && (len(rest) == 0 || rest[0] == '\n' || rest[0] == '\r')
}

// Written is Opens for a file parsed with its comments.
func Written(f *ast.File) bool {
	return f != nil && len(f.Comments) > 0 && f.Comments[0].Pos() == f.FileStart &&
		f.Comments[0].List[0].Text == Header
}

// Stale reports whether the Go file name, holding src, is output of the GALA
// transpiler left in a source tree: a `.gen.go` that opens with Header.
func Stale(name string, src []byte) bool {
	return strings.HasSuffix(name, ".gen.go") && Opens(src)
}

// StaleFile is Stale for the file at path. Only the first line is read; a file
// that cannot be read is not stale.
func StaleFile(path string) bool {
	if !strings.HasSuffix(path, ".gen.go") {
		return false
	}
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()
	head := make([]byte, len(Header)+1)
	n, err := io.ReadFull(f, head)
	if err != nil && err != io.ErrUnexpectedEOF && err != io.EOF {
		return false
	}
	return Opens(head[:n])
}
