package genheader

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestOpensAndWritten(t *testing.T) {
	tests := []struct {
		name string
		src  string
		want bool
	}{
		{"transpiler output", Header + "\n\npackage lib\n", true},
		{"transpiler output, CRLF", Header + "\r\n\r\npackage lib\r\n", true},
		{"with a package doc", Header + "\n\n// Package lib " + strings.Repeat("does things. ", 1000) + "\npackage lib\n", true},
		{"oapi-codegen", "// Package lib provides an API.\n//\n// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.\npackage lib\n", false},
		{"stringer", "// Code generated by \"stringer -type=Color\"; DO NOT EDIT.\n\npackage lib\n", false},
		{"hand-written", "package lib\n\ntype Pet struct{}\n", false},
		{"header not first", "// Copyright 2026.\n\n" + Header + "\npackage lib\n", false},
		{"header extended", Header + " Really.\npackage lib\n", false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, Opens([]byte(tt.src)), "Opens")
			f, err := parser.ParseFile(token.NewFileSet(), "", tt.src, parser.PackageClauseOnly|parser.ParseComments)
			require.NoError(t, err)
			assert.Equal(t, tt.want, Written(f), "Written")
		})
	}
}

func TestStale(t *testing.T) {
	dir := t.TempDir()
	write := func(name, content string) string {
		path := filepath.Join(dir, name)
		require.NoError(t, os.WriteFile(path, []byte(content), 0o644))
		return path
	}
	own := Header + "\n\npackage lib\n"
	foreign := "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage lib\n"

	for _, tc := range []struct {
		name, content string
		want          bool
	}{
		{"lib.gen.go", own, true},
		// A plain .go the transpiler wrote is compiled like any other.
		{"lib.go", own, false},
		{"api.gen.go", foreign, false},
	} {
		assert.Equal(t, tc.want, Stale(tc.name, []byte(tc.content)), "Stale(%s)", tc.name)
		assert.Equal(t, tc.want, StaleFile(write(tc.name, tc.content)), "StaleFile(%s)", tc.name)
	}
	assert.False(t, StaleFile(filepath.Join(dir, "missing.gen.go")))
}
