load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "concurrency",
    srcs = [
        "capture.go",
        "helpers.go",
        "shareable.go",
    ],
    importpath = "martianoff/gala/internal/transpiler/concurrency",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/parser/grammar",
        "//internal/transpiler",
        "@com_github_antlr4_go_antlr_v4//:antlr",
    ],
)

go_test(
    name = "concurrency_test",
    srcs = [
        "capture_test.go",
        "shareable_test.go",
    ],
    embed = [":concurrency"],
    deps = [
        "//internal/parser",
        "//internal/parser/grammar",
        "//internal/transpiler",
        "@com_github_antlr4_go_antlr_v4//:antlr",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
