load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "transpiler",
    srcs = [
        "go_type_info.go",
        "parser.go",
        "transpiler.go",
        "types.go",
    ],
    importpath = "martianoff/gala/internal/transpiler",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/parser",
        "//internal/transpiler/profiler",
        "@com_github_antlr4_go_antlr_v4//:antlr",
    ],
)

go_test(
    name = "merge_test",
    srcs = ["merge_test.go"],
    embed = [":transpiler"],
)
