load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "parser",
    srcs = [
        "docs.go",
        "parser.go",
    ],
    importpath = "martianoff/gala/internal/parser",
    visibility = ["//:__subpackages__"],
    deps = [
        "//galaerr",
        "//internal/parser/grammar",
        "@com_github_antlr4_go_antlr_v4//:antlr",
    ],
)

go_test(
    name = "parser_test",
    srcs = [
        "bare_lambda_param_test.go",
        "bom_test.go",
        "docs_test.go",
        "empty_line_unicode_test.go",
        "go_type_in_expression_test.go",
        "grammar_test.go",
        "parser_concurrent_test.go",
        "parser_test.go",
    ],
    embed = [":parser"],
    deps = [
        "//galaerr",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
