package generator

import (
	"bytes"
	"go/ast"
	"go/format"
	"go/token"
	"martianoff/gala/internal/transpiler"
)

type goCodeGenerator struct {
}

// NewGoCodeGenerator creates a new instance of CodeGenerator that generates Go code.
func NewGoCodeGenerator() transpiler.CodeGenerator {
	return &goCodeGenerator{}
}

// generatedHeader is the standard Go generated file header.
// This tells tools like `go generate` and IDEs that the file is auto-generated.
const generatedHeader = "// Code generated by GALA transpiler. DO NOT EDIT.\n\n"

// Generate implements the CodeGenerator interface.
//
// The pipeline is two-step:
//
//  1. format.Node prints the AST. This honours the AST's import-decl
//     order, which the transformer builds in declaration order rather
//     than gofmt-canonical order (sorted within groups).
//  2. format.Source on the printed bytes parses + re-prints with
//     gofmt's import-grouping rules. The result is gofmt-idempotent —
//     a downstream `gofmt -l` over the emitted file finds nothing to
//     change. (See `transformer/generated_format_test.go` for the
//     regression guard.)
//
// When format.Source rejects the buffer (typically because the LSP
// fed partially-valid input the transpiler can still partially handle,
// producing an AST that prints but does not re-parse), fall back to
// the format.Node output unchanged. This keeps interactive completion
// working on incomplete source while still canonicalising the
// happy-path build pipeline output.
func (g *goCodeGenerator) Generate(fset *token.FileSet, file *ast.File) (string, error) {
	var buf bytes.Buffer
	if err := format.Node(&buf, fset, file); err != nil {
		return "", err
	}
	if canonical, err := format.Source(buf.Bytes()); err == nil {
		return generatedHeader + string(canonical), nil
	}
	return generatedHeader + buf.String(), nil
}

var _ transpiler.CodeGenerator = (*goCodeGenerator)(nil)
