package generator

import (
	"bytes"
	"go/ast"
	"go/format"
	"go/token"
	"martianoff/gala/internal/transpiler"
)

type goCodeGenerator struct {
}

// NewGoCodeGenerator creates a new instance of CodeGenerator that generates Go code.
func NewGoCodeGenerator() transpiler.CodeGenerator {
	return &goCodeGenerator{}
}

// generatedHeader is the standard Go generated file header.
// This tells tools like `go generate` and IDEs that the file is auto-generated.
const generatedHeader = "// Code generated by GALA transpiler. DO NOT EDIT.\n\n"

// Generate implements the CodeGenerator interface.
func (g *goCodeGenerator) Generate(fset *token.FileSet, file *ast.File) (string, error) {
	var buf bytes.Buffer
	if err := format.Node(&buf, fset, file); err != nil {
		return "", err
	}
	return generatedHeader + buf.String(), nil
}

var _ transpiler.CodeGenerator = (*goCodeGenerator)(nil)
