load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "resolver",
    srcs = ["resolver.go"],
    importpath = "martianoff/gala/internal/transpiler/resolver",
    visibility = ["//:__subpackages__"],
    deps = ["//internal/transpiler/registry"],
)

go_test(
    name = "resolver_test",
    srcs = ["resolver_test.go"],
    embed = [":resolver"],
    deps = ["@com_github_stretchr_testify//assert"],
)
