load("@rules_go//go:def.bzl", "go_library")
load("@rules_gala//gala:defs.bzl", "gala_bootstrap_transpile", "gala_test")

exports_files([
    "future.gala",
    "event_bus.gala",
    "execution_context.go",
])

filegroup(
    name = "gala_sources",
    srcs = glob(
        ["*.gala"],
        exclude = ["*_test.gala"],
    ),
    visibility = ["//visibility:public"],
)

gala_bootstrap_transpile(
    name = "future_go",
    src = "future.gala",
    out = "future.gen.go",
)

gala_bootstrap_transpile(
    name = "retry_go",
    src = "retry.gala",
    out = "retry.gen.go",
)

gala_bootstrap_transpile(
    name = "event_bus_go",
    src = "event_bus.gala",
    out = "event_bus.gen.go",
)

go_library(
    name = "concurrent",
    srcs = [
        "event_bus.gen.go",
        "execution_context.go",
        "future.gen.go",
        "retry.gen.go",
    ],
    importpath = "martianoff/gala/concurrent",
    visibility = ["//visibility:public"],
    deps = [
        "//collection_immutable",
        "//go_interop",
        "//std",
        "//time_utils",
    ],
)

gala_test(
    name = "future_test",
    srcs = ["future_test.gala"],
    deps = [
        ":concurrent",
        "//collection_immutable",
        "//go_interop",
        "//time_utils",
    ],
)
