load("@rules_go//go:def.bzl", "go_library")

genrule(
    name = "gala_grammar_go",
    srcs = [
        "gala.g4",
        "gala_base_listener.go.src",
        "gala_lexer.go.src",
        "gala_listener.go.src",
        "gala_parser.go.src",
    ],
    outs = [
        "gala_base_listener.go",
        "gala_lexer.go",
        "gala_listener.go",
        "gala_parser.go",
    ],
    cmd = """
        cp "$(location gala_base_listener.go.src)" "$(location gala_base_listener.go)"
        cp "$(location gala_lexer.go.src)" "$(location gala_lexer.go)"
        cp "$(location gala_listener.go.src)" "$(location gala_listener.go)"
        cp "$(location gala_parser.go.src)" "$(location gala_parser.go)"
    """,
)

go_library(
    name = "grammar",
    srcs = [
        "gala_base_listener.go",
        "gala_lexer.go",
        "gala_listener.go",
        "gala_parser.go",
    ],
    importpath = "martianoff/gala/internal/parser/grammar",
    visibility = ["//visibility:public"],
    deps = ["@com_github_antlr4_go_antlr_v4//:antlr"],  # keep
)

exports_files(["gala.g4"])
