#!/usr/bin/env bash
#
# Run the transpiler's native Go fuzz targets (internal/transpiler/fuzz).
#
#   tools/fuzz.sh                                  # list the targets
#   tools/fuzz.sh FuzzStringLiterals               # fuzz one target for 10m
#   tools/fuzz.sh FuzzTranspileNoCrash 30m         # ... for a chosen time
#   tools/fuzz.sh FuzzSourceEncoding 20m -parallel 8   # extra `go test` flags
#   tools/fuzz.sh FuzzSourceEncoding -parallel 8       # ... with the default time
#
# `bazel test //internal/transpiler/fuzz:fuzz_test` runs every target over its
# seed corpus as an ordinary unit test; that is what CI does. Generating new
# inputs needs `go test -fuzz`, which builds the coverage-instrumented binary
# the fuzzer is guided by — something a Bazel go_test does not produce. Plain
# `go test` in turn needs the ANTLR parser sources, which are generated by
# Bazel and not checked in, so this script builds them first and copies them
# next to the grammar (the copies are git-ignored). Copies the script created
# are removed when it exits, so they cannot go stale after a grammar change.
#
# A failing input is written to
# internal/transpiler/fuzz/testdata/fuzz/<Target>/<hash>. Fix the bug, then
# commit that file: it becomes a permanent seed that `bazel test` replays.
#
# Set GALA_FUZZ_REQUIRE_CODES=1 to also fail on semantic diagnostics that carry
# no GALA-Exxxx code.
#
# Uses bazelisk when it is on PATH (see AGENTS.md: a directly installed Bazel
# may rewrite MODULE.bazel.lock); set BAZEL to override.
### end usage

set -euo pipefail

usage() {
  sed -n '2,/^### end usage/p' "$0" | sed -e '$d' -e 's/^# \{0,1\}//'
}

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$repo_root"

pkg=./internal/transpiler/fuzz/

if [[ $# -eq 0 || "$1" == -* ]]; then
  usage
  echo
  echo "Targets:"
  grep -ho '^func Fuzz[A-Za-z0-9_]*' internal/transpiler/fuzz/*_test.go | sed 's/^func /  /'
  exit 0
fi

target="$1"
shift
fuzztime=10m
# The time is optional: a second argument that looks like a flag is the
# first of the extra `go test` flags instead.
if [[ $# -gt 0 && "$1" != -* ]]; then
  fuzztime="$1"
  shift
fi

bazel_cmd="${BAZEL:-}"
if [[ -z "$bazel_cmd" ]]; then
  if command -v bazelisk >/dev/null 2>&1; then
    bazel_cmd=bazelisk
  else
    bazel_cmd=bazel
  fi
fi

"$bazel_cmd" build //internal/parser/grammar:gala_grammar_go
bin_dir="$("$bazel_cmd" info bazel-bin)"
created=()
cleanup() {
  if [[ ${#created[@]} -gt 0 ]]; then
    rm -f "${created[@]}"
  fi
}
trap cleanup EXIT
for f in gala_base_listener.go gala_lexer.go gala_listener.go gala_parser.go; do
  dest="internal/parser/grammar/$f"
  [[ -e "$dest" ]] || created+=("$dest")
  cp -f "$bin_dir/internal/parser/grammar/$f" "$dest"
  chmod u+w "$dest"
done

go test "$pkg" -run '^$' -fuzz "^${target}\$" -fuzztime "$fuzztime" "$@"
