package analyzer

import (
	"maps"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"martianoff/gala/internal/transpiler"
	"martianoff/gala/internal/transpiler/genheader"
)

// A .gen.go another generator wrote (oapi-codegen here) is source of its
// package like hand-written Go; only the GALA transpiler's own output, told by
// its header, restates the .gala source and is left out. Every reader of a
// package's Go files has to agree on that: the export scan (type existence for
// GALA-E0023 and dot-import collisions), the Go type analysis, the local
// declaration scan and the analysis cache's content hash.
const foreignGenGo = "// Package lib provides primitives to interact with the openapi HTTP API.\n" +
	"//\n" +
	"// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.\n" +
	"package lib\n\ntype Pet struct {\n\tName string\n}\n"

// foreignGenGoPackage is a package holding a foreign .gen.go, GALA source and
// the transpiler's own (stale) output.
var foreignGenGoPackage = map[string]string{
	"api.gen.go": foreignGenGo,
	"lib.gala":   "package lib\n\nfunc Describe(p Pet) string = p.Name\n",
	"lib.gen.go": genheader.Header + "\n\npackage lib\n\ntype Stale struct{}\n",
}

// writeForeignGenGoPackage writes files into a new directory and returns it
// with the files' infos.
func writeForeignGenGoPackage(t *testing.T, files map[string]string) (string, []os.FileInfo) {
	t.Helper()
	dir := t.TempDir()
	var infos []os.FileInfo
	for name, content := range files {
		path := filepath.Join(dir, name)
		require.NoError(t, os.WriteFile(path, []byte(content), 0o644))
		fi, err := os.Stat(path)
		require.NoError(t, err)
		infos = append(infos, fi)
	}
	return dir, infos
}

func TestForeignGenGoIsPackageSource(t *testing.T) {
	dir, infos := writeForeignGenGoPackage(t, foreignGenGoPackage)

	rich := &transpiler.RichAST{PackageName: "lib"}
	(&galaAnalyzer{}).extractGoFileExports(infos, dir, "lib", rich, false)
	assert.Equal(t, []string{"Pet"}, rich.GoExports["lib"], "export scan")

	info := AnalyzeGoFiles(dir, "example.test/lib")
	assert.Contains(t, info.Types, "lib.Pet", "Go type analysis")
	assert.NotContains(t, info.Types, "lib.Stale", "Go type analysis")

	assert.Equal(t, map[string]bool{"Pet": true}, parseLocalGoDeclNames(dir, false), "local declaration scan")
}

// The analysis cache is keyed by the content hash: editing the foreign file
// must change it, editing the transpiler's own output must not.
func TestForeignGenGoKeysAnalysisCache(t *testing.T) {
	hash := func(name, content string) string {
		files := maps.Clone(foreignGenGoPackage)
		if content == "" {
			delete(files, name)
		} else {
			files[name] = content
		}
		dir, _ := writeForeignGenGoPackage(t, files)
		return pkgFingerprintForDir(dir).contentHash
	}
	base := hash("api.gen.go", foreignGenGo)

	assert.NotEqual(t, base, hash("api.gen.go", foreignGenGo+"\ntype Owner struct{}\n"),
		"an edit of the foreign .gen.go")
	assert.Equal(t, base, hash("lib.gen.go", foreignGenGoPackage["lib.gen.go"]+"\ntype Other struct{}\n"),
		"an edit of the transpiler's own output")
	assert.Equal(t, base, hash("lib.gen.go", ""), "without the transpiler's own output")
}
