package analyzer_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"martianoff/gala/internal/transpiler/analyzer"
)

// TestAnalyzeOwnGoFiles covers which files of a directory belong to the
// package being compiled, and which type names it declares itself.
func TestAnalyzeOwnGoFiles(t *testing.T) {
	dir := t.TempDir()
	for name, src := range map[string]string{
		// The package's own file. It names container/list's types in a
		// signature, which files them under "list" — this package's name.
		"own.go": "package list\n\nimport golist \"container/list\"\n\n" +
			"type node struct{ v int }\n\n" +
			"func Front(l *golist.List) *golist.Element { return l.Front() }\n",
		// Built for some platforms only: still part of the package.
		"own_linux.go": "//go:build linux\n\npackage list\n\ntype LinuxOnly struct{}\n",
		// Never built.
		"gen.go": "//go:build ignore\n\npackage list\n\ntype Generated struct{}\n",
		// Output of the GALA transpiler.
		"old.go": "// Code generated by GALA transpiler. DO NOT EDIT.\n\npackage list\n\ntype Stale struct{}\n",
		// Another package in the same directory.
		"tool.go": "package tool\n\ntype Tool struct{}\n",
	} {
		require.NoError(t, os.WriteFile(filepath.Join(dir, name), []byte(src), 0o644))
	}

	info, ownTypes, _ := analyzer.AnalyzeOwnGoFiles(dir, "example.com/list", "list")
	assert.Equal(t, map[string]bool{"node": true, "LinuxOnly": true}, ownTypes,
		"only the types this package's own files declare, unexported ones included")
	assert.NotNil(t, info.GetFuncSignature("list.Front"))
	for _, absent := range []string{"list.Generated", "list.Stale", "tool.Tool"} {
		assert.Nil(t, info.GetTypeData(absent), "%s is not part of the package", absent)
	}
}
