package transformer_test

import (
	"os"
	"path/filepath"
	"testing"

	"martianoff/gala/internal/transpiler"
	"martianoff/gala/internal/transpiler/analyzer"
	"martianoff/gala/internal/transpiler/generator"
	"martianoff/gala/internal/transpiler/transformer"

	"github.com/stretchr/testify/assert"
)

// writeExternalLibForTest writes a fake "external Bazel module" library
// package containing only compiled Go output (no .gala source). The library
// declares:
//
//   - A zero-field generic sealed case  : QuitCmd[T]() -> Cmd[T]
//   - A generic sealed case with fields : MsgCmd[T](Val T) -> Cmd[T]
//   - A Go-style struct with an immutable string field and a func-typed field:
//     Settings[T any] { Title string; OnSelect func(T) Cmd[T] }
//
// This mirrors the layout a consumer sees when a GALA library is consumed
// across Bazel module boundaries: the consumer's --search paths cover the
// directory containing the .gen.go but the original .gala source files are
// not visible.
func writeExternalLibForTest(t *testing.T, libDir string) {
	t.Helper()
	assert.NoError(t, os.MkdirAll(libDir, 0755))
	libGo := `// Code generated by GALA transpiler. DO NOT EDIT.

package extlib

import "martianoff/gala/std"

const (
	_Cmd_QuitCmd = 1
	_Cmd_MsgCmd  = 2
)

// Sealed parent — generic.
type Cmd[T any] struct {
	_variant int
	_msgcmd  T
}

// Zero-field variant.
type QuitCmd[T any] struct{}

func (_ QuitCmd[T]) Apply() Cmd[T] {
	return Cmd[T]{_variant: _Cmd_QuitCmd}
}
func (_ QuitCmd[T]) Unapply(v Cmd[T]) bool {
	return v._variant == _Cmd_QuitCmd
}

// Variant with one field.
type MsgCmd[T any] struct{}

func (_ MsgCmd[T]) Apply(Val T) Cmd[T] {
	return Cmd[T]{_variant: _Cmd_MsgCmd, _msgcmd: Val}
}
func (_ MsgCmd[T]) Unapply(v Cmd[T]) std.Option[T] {
	if v._variant != _Cmd_MsgCmd {
		return std.None[T]{}.Apply()
	}
	return std.Some[T]{}.Apply(v._msgcmd)
}

// Go-style struct with an immutable field and a func-typed field.
type Settings[T any] struct {
	Title    std.Immutable[string]
	OnSelect func(T) Cmd[T]
}
`
	assert.NoError(t, os.WriteFile(filepath.Join(libDir, "lib.gen.go"), []byte(libGo), 0644))
}

// TestExternalLib_ZeroFieldSealedCaseLowering reproduces the BUG-10 REOPENED
// shape: a consumer dot-imports a GALA library shipped only as compiled
// .gen.go; constructing a zero-field generic sealed case via QuitCmd[int]()
// must lower to QuitCmd[int]{}.Apply(), not the bare conversion form.
func TestExternalLib_ZeroFieldSealedCaseLowering(t *testing.T) {
	tempDir, err := os.MkdirTemp("", "external_named_arg_test_a")
	assert.NoError(t, err)
	defer os.RemoveAll(tempDir)

	assert.NoError(t, os.WriteFile(filepath.Join(tempDir, "go.mod"),
		[]byte("module testmod\n\ngo 1.22\n"), 0644))
	writeExternalLibForTest(t, filepath.Join(tempDir, "extlib"))

	originalWd, err := os.Getwd()
	assert.NoError(t, err)
	defer os.Chdir(originalWd)
	assert.NoError(t, os.Chdir(tempDir))

	p := transpiler.NewAntlrGalaParser()
	a := analyzer.NewGalaAnalyzer(p, getStdSearchPath())
	tr := transformer.NewGalaASTTransformer()
	g := generator.NewGoCodeGenerator()
	trans := transpiler.NewGalaToGoTranspiler(p, a, tr, g)

	input := `package consumer

import . "testmod/extlib"

func mkQuit() Cmd[int] = QuitCmd[int]()
`
	got, err := trans.Transpile(input, "")
	assert.NoError(t, err, "transpile must succeed")

	assert.Contains(t, got, "QuitCmd[int]{}.Apply()",
		"zero-field sealed case must lower to {}.Apply(); got:\n%s", got)
	assert.NotContains(t, got, "QuitCmd[int]()",
		"zero-field sealed case must not lower to bare conversion; got:\n%s", got)
}

// TestExternalLib_SealedCaseWithFieldsNamedArg reproduces BUG-16 (FIX-020):
// constructing a sealed case with one or more fields using named-argument
// syntax against an external library must lower to Case[T]{}.Apply(v),
// NOT to a struct literal Case[T]{Field: v} (which is invalid against the
// zero-field variant struct).
func TestExternalLib_SealedCaseWithFieldsNamedArg(t *testing.T) {
	tempDir, err := os.MkdirTemp("", "external_named_arg_test_b")
	assert.NoError(t, err)
	defer os.RemoveAll(tempDir)

	assert.NoError(t, os.WriteFile(filepath.Join(tempDir, "go.mod"),
		[]byte("module testmod\n\ngo 1.22\n"), 0644))
	writeExternalLibForTest(t, filepath.Join(tempDir, "extlib"))

	originalWd, err := os.Getwd()
	assert.NoError(t, err)
	defer os.Chdir(originalWd)
	assert.NoError(t, os.Chdir(tempDir))

	p := transpiler.NewAntlrGalaParser()
	a := analyzer.NewGalaAnalyzer(p, getStdSearchPath())
	tr := transformer.NewGalaASTTransformer()
	g := generator.NewGoCodeGenerator()
	trans := transpiler.NewGalaToGoTranspiler(p, a, tr, g)

	input := `package consumer

import . "testmod/extlib"

func mkMsg() Cmd[int] = MsgCmd[int](Val = 42)
`
	got, err := trans.Transpile(input, "")
	assert.NoError(t, err, "transpile must succeed")

	assert.Contains(t, got, "MsgCmd[int]{}.Apply(42)",
		"sealed case w/ field named arg must lower to {}.Apply(42); got:\n%s", got)
	// Must NOT emit a struct literal of the variant — variant struct has no fields.
	assert.NotContains(t, got, "MsgCmd[int]{Val:",
		"sealed case named-arg must not lower to a struct literal; got:\n%s", got)
}

// TestExternalLib_GoStructNamedArgWrapsImmutables reproduces BUG-15 (FIX-019):
// constructing an external library's Go-style struct via named arguments
// must (a) wrap each immutable field value in std.NewImmutable and (b) keep
// the func-typed field's lambda parameters concretely typed (not 'any').
func TestExternalLib_GoStructNamedArgWrapsImmutables(t *testing.T) {
	tempDir, err := os.MkdirTemp("", "external_named_arg_test_c")
	assert.NoError(t, err)
	defer os.RemoveAll(tempDir)

	assert.NoError(t, os.WriteFile(filepath.Join(tempDir, "go.mod"),
		[]byte("module testmod\n\ngo 1.22\n"), 0644))
	writeExternalLibForTest(t, filepath.Join(tempDir, "extlib"))

	originalWd, err := os.Getwd()
	assert.NoError(t, err)
	defer os.Chdir(originalWd)
	assert.NoError(t, os.Chdir(tempDir))

	p := transpiler.NewAntlrGalaParser()
	a := analyzer.NewGalaAnalyzer(p, getStdSearchPath())
	tr := transformer.NewGalaASTTransformer()
	g := generator.NewGoCodeGenerator()
	trans := transpiler.NewGalaToGoTranspiler(p, a, tr, g)

	input := `package consumer

import . "testmod/extlib"

func mkSettings() Settings[int] = Settings[int](
    Title = "hello",
    OnSelect = (m) => QuitCmd[int]()
)
`
	got, err := trans.Transpile(input, "")
	assert.NoError(t, err, "transpile must succeed")

	// Title must be wrapped in std.NewImmutable so the consumer code matches
	// the field's declared type std.Immutable[string].
	assert.Contains(t, got, "NewImmutable",
		"immutable string field must be wrapped in NewImmutable; got:\n%s", got)
	// The OnSelect lambda parameter must NOT be widened to `any` — the field
	// is `func(T) Cmd[T]` with T=int, so the lambda's param type must be int.
	assert.NotContains(t, got, "func(m any)",
		"lambda parameter must not widen to 'any'; got:\n%s", got)
	assert.Contains(t, got, "func(m int)",
		"lambda parameter must be concretely typed as int; got:\n%s", got)
	// Sanity: the QuitCmd inside the lambda still lowers to {}.Apply().
	assert.Contains(t, got, "QuitCmd[int]{}.Apply()",
		"nested QuitCmd must still lower to {}.Apply(); got:\n%s", got)
}
