package transformer_test

import (
	"os"
	"path/filepath"
	"testing"

	"martianoff/gala/internal/transpiler"
	"martianoff/gala/internal/transpiler/analyzer"
	"martianoff/gala/internal/transpiler/generator"
	"martianoff/gala/internal/transpiler/transformer"

	"github.com/stretchr/testify/assert"
)

// TestPhantomReExportFromStaleGenGo_FuncOnlyPackage is the T6 fixture
// guarding the B5 fix. It complements TestDotImportPhantomReExportFromStaleGenGo
// (which exercises a *type-bearing* parent package) by stressing a parent
// package whose .gala source contributes ONLY functions — no types, no
// companion objects, no type aliases. Before B5 tightened the
// `includeGenerated` heuristic in analyzer.go, such a package fell back
// to `includeGenerated=true` because the heuristic only checked
// `len(pkgAST.Types) == 0`, re-introducing the phantom-re-export bug
// PR #237 originally fixed.
//
// Layout:
//
//	funconly/                  parent package — only `func helper(): Int = 42`
//	funconly/util.gen.go       STALE — declares a phantom `Helper` symbol
//	funconly/sub/              subpackage — re-exports `helper` cleanly
//	funconly/demo/             dot-imports both
//
// With B5: the stale .gen.go is excluded because the parent's GALA source
// contributed at least one Function. Without B5: the parent's Functions
// map is non-empty but the heuristic only looks at Types, so .gen.go is
// re-scanned and the phantom symbol clashes with the subpackage re-export.
func TestPhantomReExportFromStaleGenGo_FuncOnlyPackage(t *testing.T) {
	tempDir, err := os.MkdirTemp("", "phantom_reexport_funconly_test")
	assert.NoError(t, err)
	defer os.RemoveAll(tempDir)

	err = os.WriteFile(filepath.Join(tempDir, "go.mod"),
		[]byte("module github.com/example/funconly\n\ngo 1.22\n"), 0644)
	assert.NoError(t, err)

	// Parent package: function-only. No types, no companions, no aliases.
	// pkgAST.Types is empty — that's the precondition that defeats the
	// pre-B5 heuristic.
	err = os.WriteFile(filepath.Join(tempDir, "util.gala"), []byte(`package funconly

func helper() Int = 42
`), 0644)
	assert.NoError(t, err)

	// STALE .gen.go in the parent directory. The phantom symbol it
	// declares would, before B5, leak into the parent's exported set
	// and clash with the subpackage's re-export.
	err = os.WriteFile(filepath.Join(tempDir, "phantom.gen.go"), []byte(`// Code generated by GALA transpiler. DO NOT EDIT.

package funconly

func PhantomHelper() int {
	return 99
}
`), 0644)
	assert.NoError(t, err)

	// Subpackage: dot-imports the parent and exposes its own re-export
	// under the same `PhantomHelper` name. With B5, this is fine —
	// the parent's stale .gen.go is excluded so PhantomHelper is owned
	// only by the subpackage. Without B5, both the parent (via stale
	// .gen.go) and the subpackage would claim it, tripping the dot-
	// import collision check.
	subDir := filepath.Join(tempDir, "sub")
	err = os.MkdirAll(subDir, 0755)
	assert.NoError(t, err)
	err = os.WriteFile(filepath.Join(subDir, "extra.gala"), []byte(`package sub

import . "github.com/example/funconly"

func PhantomHelper() Int = helper() + 1
`), 0644)
	assert.NoError(t, err)

	// Demo consumer lives in its own subdirectory so it doesn't share the
	// parent's package name.
	demoDir := filepath.Join(tempDir, "demo")
	err = os.MkdirAll(demoDir, 0755)
	assert.NoError(t, err)
	demoFile := filepath.Join(demoDir, "demo.gala")
	err = os.WriteFile(demoFile, []byte(`package demo

import (
    . "github.com/example/funconly"
    . "github.com/example/funconly/sub"
)

func use() Int = helper() + PhantomHelper()
`), 0644)
	assert.NoError(t, err)

	originalWd, err := os.Getwd()
	assert.NoError(t, err)
	defer os.Chdir(originalWd)
	err = os.Chdir(tempDir)
	assert.NoError(t, err)

	p := transpiler.NewAntlrGalaParser()
	a := analyzer.NewGalaAnalyzer(p, nil)
	tr := transformer.NewGalaASTTransformer()
	g := generator.NewGoCodeGenerator()
	trans := transpiler.NewGalaToGoTranspiler(p, a, tr, g)

	demoSrc, err := os.ReadFile(demoFile)
	assert.NoError(t, err)
	_, err = trans.Transpile(string(demoSrc), demoFile)
	assert.NoError(t, err,
		"function-only parent package's stale .gen.go must be excluded so dot-imports do not collide on PhantomHelper")
}
