package transformer_test

import (
	"os"
	"path/filepath"
	"testing"

	"martianoff/gala/internal/transpiler"
	"martianoff/gala/internal/transpiler/analyzer"
	"martianoff/gala/internal/transpiler/generator"
	"martianoff/gala/internal/transpiler/transformer"

	"github.com/stretchr/testify/assert"
)

// TestSealedCaseExternalDotImport reproduces the scenario where a consumer
// dot-imports a GALA library whose package directory only contains compiled
// .gen.go files (no .gala source) — the typical layout when the library is
// pulled in as a separate Bazel module. Constructing a zero-field generic
// sealed case via Case[T]() must lower to Case[T]{}.Apply(); otherwise Go
// reads it as a type conversion on an empty struct and refuses to compile.
func TestSealedCaseExternalDotImport(t *testing.T) {
	tempDir, err := os.MkdirTemp("", "sealed_external_dot_import_test")
	assert.NoError(t, err)
	defer os.RemoveAll(tempDir)

	err = os.WriteFile(filepath.Join(tempDir, "go.mod"), []byte("module testmod\n\ngo 1.22\n"), 0644)
	assert.NoError(t, err)

	// Library package shipped as a compiled Go file only — mirrors the way an
	// external Bazel module is consumed (only .gen.go is visible to the
	// downstream analyzer; the original .gala source lives in a separate
	// repository cache that the consumer's --search paths don't cover).
	libDir := filepath.Join(tempDir, "extlib")
	err = os.MkdirAll(libDir, 0755)
	assert.NoError(t, err)
	err = os.WriteFile(filepath.Join(libDir, "lib.gen.go"), []byte(`// Code generated by GALA transpiler. DO NOT EDIT.

package extlib

const (
	_Cmd_QuitCmd = 1
	_Cmd_NoCmd   = 2
	_Cmd_MsgCmd  = 3
)

type Cmd[T any] struct {
	_variant int
	_msgcmd  T
}

type QuitCmd[T any] struct{}

func (_ QuitCmd[T]) Apply() Cmd[T] {
	return Cmd[T]{_variant: _Cmd_QuitCmd}
}
func (_ QuitCmd[T]) Unapply(v Cmd[T]) bool {
	return v._variant == _Cmd_QuitCmd
}

type NoCmd[T any] struct{}

func (_ NoCmd[T]) Apply() Cmd[T] {
	return Cmd[T]{_variant: _Cmd_NoCmd}
}
func (_ NoCmd[T]) Unapply(v Cmd[T]) bool {
	return v._variant == _Cmd_NoCmd
}
`), 0644)
	assert.NoError(t, err)

	originalWd, err := os.Getwd()
	assert.NoError(t, err)
	defer os.Chdir(originalWd)
	err = os.Chdir(tempDir)
	assert.NoError(t, err)

	p := transpiler.NewAntlrGalaParser()
	a := analyzer.NewGalaAnalyzer(p, getStdSearchPath())
	tr := transformer.NewGalaASTTransformer()
	g := generator.NewGoCodeGenerator()
	trans := transpiler.NewGalaToGoTranspiler(p, a, tr, g)

	// Consumer dot-imports the prebuilt library and constructs zero-field
	// sealed cases via Case[T]().
	input := `package consumer

import . "testmod/extlib"

func makeQuit() Cmd[int] = QuitCmd[int]()
func makeNoop() Cmd[int] = NoCmd[int]()
`

	got, err := trans.Transpile(input, "")
	assert.NoError(t, err, "transpile must succeed")

	// Generated Go must use the {}.Apply() shape — otherwise Go interprets
	// QuitCmd[int]() as a conversion to the empty-struct type.
	assert.Contains(t, got, "QuitCmd[int]{}.Apply()",
		"makeQuit should lower to QuitCmd[int]{}.Apply(); got:\n%s", got)
	assert.Contains(t, got, "NoCmd[int]{}.Apply()",
		"makeNoop should lower to NoCmd[int]{}.Apply(); got:\n%s", got)
	// The bare conversion form must NOT appear.
	assert.NotContains(t, got, "QuitCmd[int]()",
		"must not emit bare QuitCmd[int]() conversion form; got:\n%s", got)
	assert.NotContains(t, got, "NoCmd[int]()",
		"must not emit bare NoCmd[int]() conversion form; got:\n%s", got)
}
