package transformer_test

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/bazelbuild/rules_go/go/tools/bazel"
)

// generatedHeader is the header prepended to generated Go code.
// This must match the constant in generator.go.
const generatedHeader = "// Code generated by GALA transpiler. DO NOT EDIT.\n\n"

// stripGeneratedHeader removes the generated file header from output for test comparison.
// This allows tests to focus on the generated code content without repeating the header.
func stripGeneratedHeader(s string) string {
	return strings.TrimPrefix(s, generatedHeader)
}

// itoa converts an int to its decimal string without pulling in strconv.
// Shared across the transformer test package (e.g. for embedding line numbers
// in expected output); handles negative values.
func itoa(i int) string {
	if i == 0 {
		return "0"
	}
	neg := i < 0
	if neg {
		i = -i
	}
	var buf [20]byte
	n := len(buf)
	for i > 0 {
		n--
		buf[n] = byte('0' + i%10)
		i /= 10
	}
	if neg {
		n--
		buf[n] = '-'
	}
	return string(buf[n:])
}

// getStdSearchPath returns the search path for the std package.
// In Bazel tests, it uses runfiles to find the std directory.
// Outside of Bazel, it falls back to finding go.mod and using the module root.
func getStdSearchPath() []string {
	// Try to find std in Bazel runfiles - use a known file to get the directory
	if stdFilePath, err := bazel.Runfile("std/option.gala"); err == nil {
		stdDir := filepath.Dir(stdFilePath)
		return []string{filepath.Dir(stdDir)} // Return parent of std dir
	}

	// Fallback: walk up to find go.mod (works when running outside Bazel)
	cwd, err := os.Getwd()
	if err != nil {
		return nil
	}

	dir := cwd
	for {
		modPath := filepath.Join(dir, "go.mod")
		if _, err := os.Stat(modPath); err == nil {
			return []string{dir}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}

	return nil
}
