load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "scopewalk",
    srcs = ["scopewalk.go"],
    importpath = "martianoff/gala/internal/transpiler/scopewalk",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/interpolation",
        "//internal/parser",
        "//internal/parser/grammar",
        "@com_github_antlr4_go_antlr_v4//:antlr",
    ],
)

go_test(
    name = "scopewalk_test",
    srcs = ["scopewalk_test.go"],
    deps = [
        ":scopewalk",
        "//internal/parser",
        "//internal/parser/grammar",
        "@com_github_antlr4_go_antlr_v4//:antlr",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
